// src/components/Changelog.vue
<template>
  <div class="changelog">
    <h3 @click="toggleExpand" class="changelog-title">
      <span class="changelog-arrow">{{ isExpanded ? '▼' : '▶' }}</span>
      更新日志
    </h3>
    <div
      v-if="isExpanded"
      class="changelog-content markdown-content"
      v-html="htmlContent"
    ></div>
  </div>
</template>

<script setup lang="ts">
  import { ref } from 'vue';
  import { html } from '../../CHANGELOG.md';

  const isExpanded = ref(false);

  const toggleExpand = () => {
    isExpanded.value = !isExpanded.value;
  };

  const htmlContent = html;
</script>

// src/components/Changelog.tsx
import { FunctionComponent } from 'preact';
import { useState } from 'preact/hooks';
import { html } from '../../CHANGELOG.md';

export const Changelog: FunctionComponent = () => {
  const [isExpanded, setIsExpanded] = useState(false);

  const toggleExpand = () => {
    setIsExpanded(!isExpanded);
  };

  return (
    <div className="changelog">
      <h3 onClick={toggleExpand} className="changelog-title">
        <span className="changelog-arrow">{isExpanded ? '▼' : '▶'}</span>
        更新日志
      </h3>
      {isExpanded && (
        <div className="changelog-content markdown-content" dangerouslySetInnerHTML={{ __html: html }} />
      )}
    </div>
  );
};
