// src/components/SolutionDisplay.vue
<template>
  <div class="solution-section">
    <h2>解法展示</h2>
    <div class="chessboard-display">
      <ChessboardDisplay
        :fen="fenCode"
        :bestMove="isGameOver ? '' : bestMove"
        @fenUpdate="onFenUpdate"
      />
    </div>
    <div class="solution-controls">
      <button @click="onPreviousMove" :disabled="moveHistory.length === 0">
        上一步
      </button>
      <button
        @click="onNextMove"
        :disabled="isCalculating || !bestMove || isGameOver"
      >
        下一步
      </button>
    </div>
    <div class="solution-debug">
      <p v-if="isCalculating">正在计算最佳走法...</p>
      <p v-if="error" :style="{ color: 'red' }">{{ error }}</p>
      <p v-if="!isGameOver && bestMove">
        {{ currentMoveColor }}最佳走法：
        {{ moveToChineseNotation(fenCode, bestMove) }} （第
        {{ currentMoveNumber }} 步）
      </p>
      <p v-if="isGameOver" :style="{ fontWeight: 'bold', color: 'green' }">
        {{ gameOverMessage }}
      </p>
    </div>
    <div class="move-list">
      <span v-for="(move, index) in moveItems" :key="index" class="move-item">
        {{ move }}
      </span>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { computed } from 'vue';
  import ChessboardDisplay from './ChessboardDisplay.vue';
  import { moveToChineseNotation } from '../chessboard/moveHelper';

  interface SolutionDisplayProps {
    bestMove: string;
    isCalculating: boolean;
    error: string | null;
    onNextMove: () => void;
    onPreviousMove: () => void;
    moveHistory: string[];
    fenCode: string;
    fenHistory: string[];
    onFenUpdate: (newFen: string) => void;
  }

  const props = defineProps<SolutionDisplayProps>();

  const currentMoveColor = computed(() =>
    props.moveHistory.length % 2 === 0 ? '红方' : '黑方'
  );
  const currentMoveNumber = computed(() => props.moveHistory.length + 1);

  const moveItems = computed(() =>
    props.moveHistory.map((move, index) => {
      const fenBeforeMove = props.fenHistory[index];
      return moveToChineseNotation(fenBeforeMove, move);
    })
  );

  const isGameOver = computed(
    () => props.bestMove === 'red_wins' || props.bestMove === 'black_wins'
  );
  const gameOverMessage = computed(() =>
    props.bestMove === 'red_wins'
      ? '红方胜'
      : props.bestMove === 'black_wins'
        ? '黑方胜'
        : ''
  );
</script>

// src/components/SolutionDisplay.tsx
import { ChessboardDisplay } from './ChessboardDisplay';
import { moveToChineseNotation } from '../chessboard/moveHelper';

interface SolutionDisplayProps {
  bestMove: string;
  isCalculating: boolean;
  error: string | null;
  onNextMove: () => void;
  onPreviousMove: () => void;
  moveHistory: string[];
  fenCode: string;
  fenHistory: string[];
  onFenUpdate: (newFen: string) => void;
}

export function SolutionDisplay({
  bestMove,
  isCalculating,
  error,
  onNextMove,
  onPreviousMove,
  moveHistory,
  fenCode,
  fenHistory,
  onFenUpdate,
}: SolutionDisplayProps) {
  const currentMoveColor = moveHistory.length % 2 === 0 ? '红方' : '黑方';
  const currentMoveNumber = moveHistory.length + 1;

  // Create move history items
  const moveItems = moveHistory.map((move, index) => {
    const fenBeforeMove = fenHistory[index]; // FEN before the move
    const notation = moveToChineseNotation(fenBeforeMove, move);
    return (
      <span key={index} className="move-item">
        {notation}
      </span>
    );
  });

  const isGameOver = bestMove === 'red_wins' || bestMove === 'black_wins';
  const gameOverMessage =
    bestMove === 'red_wins'
      ? '红方胜'
      : bestMove === 'black_wins'
      ? '黑方胜'
      : '';

  return (
    <div className="solution-section">
      <h2>解法展示</h2>
      <div className="chessboard-display">
        <ChessboardDisplay
          fen={fenCode}
          bestMove={isGameOver ? '' : bestMove}
          onFenUpdate={onFenUpdate}
        />
      </div>
      <div className="solution-controls">
        <button onClick={onPreviousMove} disabled={moveHistory.length === 0}>
          上一步
        </button>
        <button
          onClick={onNextMove}
          disabled={isCalculating || !bestMove || isGameOver}
        >
          下一步
        </button>
      </div>
      <div className="solution-debug">
        {isCalculating && <p>正在计算最佳走法...</p>}
        {error && <p style={{ color: 'red' }}>{error}</p>}
        {!isGameOver && bestMove && (
          <p>
            {currentMoveColor}最佳走法：
            {moveToChineseNotation(fenCode, bestMove)} （第 {currentMoveNumber}{' '}
            步）
          </p>
        )}
        {isGameOver && (
          <p style={{ fontWeight: 'bold', color: 'green' }}>
            {gameOverMessage}
          </p>
        )}
      </div>
      <div className="move-list">{moveItems}</div>
    </div>
  );
}
